language: c++

cache:
    ccache: true
    directories:
        - $HOME/homebrew_cache

before_script:
    - mkdir build ; cd build
    - CC=clang CXX=clang++ CXXFLAGS="-g -msse -msse2" cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX="" -DLLVM_CCACHE_BUILD=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_CXX1Y=ON -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_RUNTIME=OFF -DLLVM_BUILD_TOOLS=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_TOOLS=OFF -DLLVM_INCLUDE_UTILS=OFF -DWITH_POLLY=OFF

script:
    - ninja -j 2

after_script:
    - DESTDIR=./dest ninja install
    - cd dest
    - tar -czf llvmlibs-linux.tar.gz lib include bin
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - export UPLOADTOOL_SUFFIX=linux-release_60
    - bash upload.sh ./llvmlibs-linux.tar.gz
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - libstdc++-5-dev
            - ninja-build
